<?php

namespace Smc\Module\ArticleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ModuleArticleConfigurationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleArticleConfigurationRepository extends EntityRepository
{
}