<?php

namespace Smc\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ModulesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModulesRepository extends EntityRepository
{
}