<?php

namespace Smc\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

use Smc\Module\MenuBundle\Entity\ModuleMenuItems;

/**
 * PlacementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlacementRepository extends EntityRepository
{
	public function findModules($position, ModuleMenuItems $page)
	{
		 //array("ordre" => "asc")
		 
		 $qb = $this->createQueryBuilder("p");
		 
		 return $qb->getQuery()->getResult();
	}
}