<?php

namespace Smc\Module\MenuBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ModuleMenuItemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleMenuItemsRepository extends EntityRepository
{
}