<?php

namespace Smc\Module\PhotoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ModulePhotoConfigurationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModulePhotoConfigurationRepository extends EntityRepository
{
}