parameters:
#    smc_module_container_module.example.class: Smc\Module\ContainerModuleBundle\Example

services:
#    smc_module_container_module.example:
#        class: %smc_module_container_module.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
